// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoVIg9Z84Almingc6Vc4SVN-KGm_sP9Os',
    appId: '1:155681186435:web:facc57f593cca575ab31b6',
    messagingSenderId: '155681186435',
    projectId: 'kitapla-691fa',
    authDomain: 'kitapla-691fa.firebaseapp.com',
    storageBucket: 'kitapla-691fa.firebasestorage.app',
    measurementId: 'G-0SFYZCLTZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC21iwuU-u_tMhJzVXpHRwvirGjW34ai8',
    appId: '1:155681186435:android:c9dc579a898df197ab31b6',
    messagingSenderId: '155681186435',
    projectId: 'kitapla-691fa',
    storageBucket: 'kitapla-691fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcdMTDhqfwnVQPYggWSB9qdxIfMAZ6ij0',
    appId: '1:155681186435:ios:5e5b4a96a4e522e1ab31b6',
    messagingSenderId: '155681186435',
    projectId: 'kitapla-691fa',
    storageBucket: 'kitapla-691fa.firebasestorage.app',
    androidClientId: '155681186435-ta9aked04k6cjkvpn2vin4fgpi4qlcn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitapla',
  );
}
